### ISSUE TITLE
Exception on multiline field

### ISSUE THREAD

**Issue by savearray2** [eno-lang/enolib#3]
```
# section test
hello: 123
goodbye:
	- 1
	- 2
	-
	- 4
empty:

-- multifield
this is a
multiline
field.
-- multifield
```

Currently getting the following error on the eno above:

```
/Users/dict/git/eno-extensions/node_modules/enolib/lib/context.js:245
            element.computedValue = this._input.substring(
                                                ^

TypeError: this._input.substring is not a function
    at Context.value (/Users/dict/git/eno-extensions/node_modules/enolib/lib/context.js:245:49)
    at Field._value (/Users/dict/git/eno-extensions/node_modules/enolib/lib/elements/field.js:13:33)
    at Field.optionalStringValue (/Users/dict/git/eno-extensions/node_modules/enolib/lib/elements/field.js:33:17)
    at tokenizer (/Users/dict/git/eno-extensions/js/deserialize.js:48:24)
    at tokenizer (/Users/dict/git/eno-extensions/js/deserialize.js:41:24)
    at tokenizer (/Users/dict/git/eno-extensions/js/deserialize.js:45:24)
    at tokenizer (/Users/dict/git/eno-extensions/js/deserialize.js:41:24)
    at module.exports (/Users/dict/git/eno-extensions/js/deserialize.js:64:9)
    at Function.Deserialize (/Users/dict/git/eno-extensions/index.js:44:10)
    at Object.<anonymous> (/Users/dict/git/eno-extensions/local/t.js:8:17)
```

**Comment by simonrepp** [comment]
Oh whoops, will look into this first thing when I come back from my errands,
looks like a undiscovered side-effect of some recent refactoring.

Thanks!

**Comment by savearray2** [comment]
No problem! Just running some tests myself :)

**Comment by savearray2** [comment]
I'll see if I can reproduce in a simpler environment in a second. I do seem to be using 0.30:
```
	"dependencies": {
		"enolib": "^0.3.0",
```

**Comment by savearray2** [comment]
Well... That's strange. I can't actually reproduce the problem, even though I double checked a few times before I posted. It's possible there was a Japanese character (a space or something) that caused the problem, but I still can't duplicate, even entering random data

I expect to be running more tests, so if I see it pop up again, I'll let you know. Sorry about that. I should have saved that exact code.

You can close this for now if you'd like. :)

**Comment by simonrepp** [comment]
No worries, we'll look at it when it reappears. :) thanks for checking!
